# Site
repository: myakisheff/myakisheff.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Мякишев Никита
title: Android Developer
email: n.s.myakishev@yandex.ru
phone: 
website:

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username:
github_username:  myakisheff
stackoverflow_username: 
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/myakishef

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content:
  За время своего обучения пробовал различные направления, а именно разработку Desktop приложений на C++ и C# и WEB-разработку, но в конечном итоге остановился на Android, так как это направление более близко мне.

content:
  - title: Скиллы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Android
        description: | # this will include new lines to allow paragraphs
        #### Android
          - UI: Jetpack Compose, Material, View Binding
          - DI: Koin
          - Сеть: Retrofit, OkHttp
          - Потоки данных: Coroutines
          - Хранение данных: Room, Jetpack DataStore

        #### Архитектура
          - MVVM, MVI, Clean

        #### Инструментарий
          - Github, Figma
  - title: Участие в мероприятиях
    layout: text
    content: | # this will include new lines to allow paragraphs
            - [Сертификат](https://disk.yandex.ru/d/ZldYG7hzEbXMZA) участника Зимней школы по программной инженерии НИУ ВШЭ - 2024
            - Тренировки по алгоритмам 5.0 (Тренировки по алгоритмам от Яндекса)
            - Активно посещаю конференции по мобильной разработке
  - title: Образование
    layout: list
    content:
      - layout: left
        title: Московский политехнический университет
        sub_title: Бакалавриат "Информатика и вычислительная техника"
        caption: 2021 - 2025
        description: | # this will include new lines to allow paragraphs
          За время обучения успел попробовать множество направлений и языков, прежде чем нашёл себя в мобильной разработке.

          В процессе обучение разработал следующие проекты:
            - MFC приложение по работе с API Inventor и Компас-3D (C++)
            - Быстрый просмотрщик изображений в проводнике с кешированием (WPF/C#)
            - Клиент-серверное веб-приложение по просмотру 3D моделей (Three.js)
            - VR приложение с использованием отслеживания рук (Unity/C#)

# Footer
footer_show_references: true
references_title:

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
